### ISSUE TITLE
Item conflict with Dino bones from another mod

### ISSUE THREAD

**Issue by CrazedKitty1290** [sor1n/Jewelrycraft#6]
I believe there's some sort of conflict with either JurassiCraft or Fossils and Archaeology Revival mod. I'm not sure which one it is, but it's conflicting with the item "Dinosaur Bones" and it's causing a NullPointerException during game start-up and it crashes before Minecraft can even get to the start menu. Here's the crash report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/27/15 5:11 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at mods.fossil.items.ItemDinosaurBones.func_150895_a(ItemDinosaurBones.java:58)
    at darkknight.jewelrycraft.util.JewelrycraftUtil.addStuff(JewelrycraftUtil.java:56)
    at darkknight.jewelrycraft.proxy.ClientProxy.postInit(ClientProxy.java:90)
    at darkknight.jewelrycraft.events.EventList.postInit(EventList.java:49)
    at darkknight.jewelrycraft.JewelrycraftMod.postInit(JewelrycraftMod.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:530)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:215)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:701)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:304)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by sor1n** [comment]
I know exactly what the problem might be. Will be fixed in the next version. Thank you for letting me know ^^

**Comment by sor1n** [comment]
Should be fixed in the new version. Please let me know.

**Comment by CrazedKitty1290** [comment]
I'm afraid it's still not working. I know it's Fossils and Archeology mod after some trail and error to be absolutely sure. I'm still getting the same crash error.
